---
  mariadb_mysql_server: "yes"

 #mariadb_mysql: to de defined in host_vars
 # for mysql < 5.6 or mariadb : use mariadb
 #mariadb_mysql: "mariadb"
 # for mysql >= 5.6 : use mysql
 #mariadb_mysql: "mysql"
