---

  - name: "{{ mariadb_mysql }} base packages"
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items: "{{ mariadb_base_packages }}"

  - name: "setting the root password for all hosts"
    mysql_user:
      user: "root"
      password: "{{ mysql_root_password }}"
      host_all: yes

  - name: .my.cnf file with root password credentials for ansible
    template:
      src: "my.cnf.j2"
      dest: "/root/.my.cnf"
      owner: "root"
      mode: "0600"

  - name: file with root password credentials for others
    template:
      src: "my.cnf.j2"
      dest: "/etc/mysql/conf.d/root.cnf"
      owner: "root"
      mode: "0600"

  - name: "removing the test database"
    mysql_db:
      db: test
      state: absent

  - name: "removing anonymous user"
    mysql_user:
      name: ''
      host_all: yes
      state: absent

  - name: "template for backup"
    template:
      src: backupninja.mariadb-mysql.j2
      dest: "{{ backup_item_dir }}/10-mariadb-mysql.sh"
      mode: 0640

  - name: "template for monitoring mariadb"
    template:
      src: "mariadb-mysql.monit.j2"
      dest: "/etc/monit/conf.d/mariadb-mysql.conf"
    notify: reload monit



