---

  app_program: "Nextcloud"
  log_type: "install"

  nextcloud_default_admin: "admin"
  nextcloud_default_password: "admin"

  app_instance_root: "{{ www_root }}/{{ app_instance_id }}"
  app_instance_www_root: "{{ app_instance_root }}"
  app_data: "{{ www_root }}/{{ app_instance_id }}.data"

  database_name: "{{ app_instance_id }}_db"
  database_user: "{{ app_instance_id }}_usr"
  database_password: "{{ app_instance_id }}_pwd"
  database_type: "postgres"

  monit_request: "https://{{ app_domain }}/index.php/login"
  # monit_expect: ""