---


  app_domain: "dolibarr-test-2.paquerette.eu"

  app_name: "dolibarr"
  app_src: "https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/6.0.3/dolibarr-6.0.3.tgz/download"
  app_src_root_name: "dolibarr-6.0.3"

  app_version: 6.0.3

  app_instance_root: "{{ www_root }}/{{ app_instance_id }}"

#  app_instance_www_root: "{{ app_instance_root }}"
  app_instance_www_root: "{{ app_instance_root }}/htdocs"

  app_instance_id: "{{ app_name }}_paq_test_2"

  instance_database_name: "{{ app_instance_id }}_db"
  instance_database_user: "{{ app_instance_id }}_usr"
  instance_database_password: "{{ app_instance_id }}_pwd"

  #app_htdocs: "htdocs"