---

  - name: "PHP packages"
    apt: name="{{ item }}" state=present
    with_items: "{{ php_nginx_packages_list }}"

  - name: "template for monitoring php{{ php_version }}-fpm"
    template:
      src: "php{{ php_version }}-fpm_monit.j2"
      dest: "/etc/monit/conf.d/php{{ php_version }}.conf"
    notify: reload monit

#  - name: cron stop php{{ php_version }}.service for backup
#    cron:
#      name: "stop php{{ php_version }}"
#      hour: "{{ backup_web_stop_hour }}"
#      minute: "{{ backup_web_stop_minute }}"
#      job: "/bin/systemctl stop php{{ php_version }}.service"
#
#  - name: cron start running php{{ php_version }}.service for backup
#    cron:
#      name: "start php{{ php_version }}"
#      hour: "{{ backup_web_start_hour }}"
#      minute: "{{ backup_web_start_minute }}"
#      job: "/bin/systemctl start php{{ php_version }}.service"

  - name: "redis server"
    apt: name="redis-server" state=present

  - name: "cron stop redis.service for backup"
    cron:
      name: "stop redis"
      hour: "{{ backup_web_stop_hour }}"
      minute: "{{ backup_web_stop_minute }}"
      job: "/bin/systemctl stop redis.service"

  - name: "cron start redis.service for backup"
    cron:
      name: "start redis"
      hour: "{{ backup_web_start_hour }}"
      minute: "{{ backup_web_start_minute }}"
      job: "/bin/systemctl start redis.service"

  - name: "template for monitoring redis"
    template:
      src: "redis_monit.j2"
      dest: "/etc/monit/conf.d/redis.conf"
    notify: reload monit

  - name: "OP Cache for PHP{{ php_version }}"
    lineinfile:
      line: "opcache.enable=1"
      insertafter: ";opcache.enable="
      path: "{{ php_ini_file }}"
      state: present
      backup: yes
    notify: reload php7.0-fpm

  - name: "OP Cache for PHP{{ php_version }}"
    lineinfile:
      line: "opcache.enable_cli=1"
      insertafter: ";opcache.enable_cli="
      path: "{{ php_ini_file }}"
      state: present
    notify: reload php7.0-fpm

  - name: "OP Cache for PHP{{ php_version }}"
    lineinfile:
      line: "opcache.memory_consumption=128"
      insertafter: ";opcache.memory_consumption"
      path: "{{ php_ini_file }}"
      state: present
    notify: reload php7.0-fpm

  - name: "OP Cache for PHP{{ php_version }}"
    lineinfile:
      line: "opcache.interned_strings_buffer=8"
      insertafter: ";opcache.interned_strings_buffer"
      path: "{{ php_ini_file }}"
      state: present
    notify: reload php7.0-fpm

  - name: "OP Cache for PHP{{ php_version }}"
    lineinfile:
      line: "opcache.max_accelerated_files=10000"
      insertafter: ";opcache.max_accelerated_files"
      path: "{{ php_ini_file }}"
      state: present
    notify: reload php7.0-fpm

#  - name: "OP Cache for PHP{{ php_version }}"
#    lineinfile:
#      line: "opcache.save_comments=1"
#      insertafter: ";opcache.save_comments"
#      path: "{{ php_ini_file }}"
#      state: present
#    notify: reload php7.0-fpm
#
  - name: "OP Cache for PHP{{ php_version }}"
    lineinfile:
      line: "opcache.revalidate_freq=1"
      insertafter: ";opcache.revalidate_freq"
      path: "{{ php_ini_file }}"
      state: present
    notify: reload php7.0-fpm

  - name: "cgi.fix_pathinfo=0 for PHP{{ php_version }}"
    lineinfile:
      line: "cgi.fix_pathinfo=0"
      insertafter: ";cgi.fix_pathinfo"
      path: "{{ php_ini_file }}"
      state: present
    notify: reload php7.0-fpm

  - name: "env[HOSTNAME] for PHP{{ php_version }}"
    lineinfile:
      line: "env[HOSTNAME] = $HOSTNAME"
      insertafter: ";env\\[HOSTNAME\\] = \\$HOSTNAME"
      path: "{{ php_www_conf_file }}"
      state: present
      backup: yes
    notify: reload php7.0-fpm

  - name: "env[PATH] for PHP{{ php_version }}"
    lineinfile:
      line: "env[PATH] = /usr/local/bin:/usr/bin:/bin"
      insertafter: ";env\\[PATH\\] = /usr/local/bin:/usr/bin:/bin"
      path: "{{ php_www_conf_file }}"
      state: present
    notify: reload php7.0-fpm

  - name: "env[TMP] for PHP{{ php_version }}"
    lineinfile:
      line: "env[TMP] = /tmp"
      insertafter: ";env\\[TMP\\] = /tmp"
      path: "{{ php_www_conf_file }}"
      state: present
    notify: reload php7.0-fpm

  - name: "env[TMPDIR] for PHP{{ php_version }}"
    lineinfile:
      line: "env[TMPDIR] = /tmp"
      insertafter: ";env\\[TMPDIR\\] = /tmp"
      path: "{{ php_www_conf_file }}"
      state: present
    notify: reload php7.0-fpm

  - name: "env[TEMP] for PHP{{ php_version }}"
    lineinfile:
      line: "env[TEMP] = /tmp"
      insertafter: ";env\\[TEMP\\] = /tmp"
      path: "{{ php_www_conf_file }}"
      state: present
    notify: reload php7.0-fpm
