---

  - include_role:
      name: nextcloud_instance
    vars:
      app_domain: "{{ item.nextcloud_domain}}"
      app_instance_id: "{{ item.nextcloud_instance_id }}"
      app_version: "{{ item.nextcloud_version }}"
      database_type: "{{ item.nextcloud_database_type }}"
    when: item.nextcloud_oldversion == ""
    loop: "{{ nextcloud_instances }}"

  - include_role:
      name: nextcloud_instance_upg
    vars:
      app_domain: "{{ item.nextcloud_domain}}"
      app_instance_id: "{{ item.nextcloud_instance_id }}"
      app_version: "{{ item.nextcloud_version }}"
      app_oldversion: "{{ item.nextcloud_oldversion }}"
      database_type: "{{ item.nextcloud_database_type }}"
    when: item.nextcloud_oldversion != ""
    loop: "{{ nextcloud_instances }}"
