---

  - include_role:
      name: nextcloud_instance
    vars:
      app_domain: "{{ inst.nextcloud_domain}}"
      app_instance_id: "{{ inst.nextcloud_instance_id }}"
      app_version: "{{ inst.nextcloud_version }}"
      app_oldversion: "{{ inst.nextcloud_oldversion }}"
    when: inst.run == "install"
    loop: "{{ nextcloud_instances }}"
    loop_control:
      loop_var: inst

  - include_role:
      name: nextcloud_instance_upg
    vars:
      app_domain: "{{ inst.nextcloud_domain}}"
      app_instance_id: "{{ inst.nextcloud_instance_id }}"
      app_version: "{{ inst.nextcloud_version }}"
      app_oldversion: "{{ inst.nextcloud_oldversion }}"
    when: inst.run == "upgrade"
    loop: "{{ nextcloud_instances }}"
    loop_control:
      loop_var: inst
