---

  - name: "template check log"
    template:
      src: app_check.j2
      dest: "{{ base_prod_ansible_log }}/{{ app_instance_id }}.log"

  - name: "fetch check log"
    fetch:
      src: "{{ base_prod_ansible_log }}/{{ app_instance_id }}.log"
      dest: "{{ app_instance_id }}.log"
      flat: yes

  - include_role:
      name: _letsencrypt_certificate
    vars:
      letsencrypt_domain: "{{ app_domain }}"

  - include_role:
      name: _create_database

  - name: create temporary download directory
    tempfile:
      state: directory
      suffix: "_app_new"
    register: _tmp_new_app
    changed_when: False

  - name: "retrieving app version {{ app_version }} in {{ _tmp_new_app.path }}"
    unarchive:
      src: "{{ app_src }}"
      dest: "{{ _tmp_new_app.path }}"
      remote_src: True
      group: "www-data"
      owner: "www-data"
    args:
      creates: "{{ app_instance_root }}"

  - name: "Move {{ _tmp_new_app.path }}/{{ app_src_root_name }} to {{ app_instance_root }}"
    command: "/bin/mv {{ _tmp_new_app.path }}/{{ app_src_root_name }} {{ app_instance_root }}"
    args:
      creates: "{{ app_instance_root }}"

  - name: "remove {{ _tmp_new_app.path }}"
    file:
      path: "{{ _tmp_new_app.path }}"
      state: absent
    changed_when: False

  - include_role:
      name: _app_backup

  - name: "log dest {{ www_log }}/{{ app_instance_id }}"
    file:
      state: directory
      path: "{{ www_log }}/{{ app_instance_id }}"

  - name: "template app_{{ rev_proxy }}.j2 {{ app_instance_id }}"
    template:
      src: "app_{{ rev_proxy }}.j2"
      dest: "/etc/{{ rev_proxy }}/sites-available/{{ app_instance_id }}.conf"
    notify: reload {{ rev_proxy }}

  - name: "logrotate for log {{ rev_proxy }} log_dest /{{ app_instance_id }}"
    template:
      src: app_logrotate_{{ rev_proxy }}.j2
      dest: "/etc/logrotate.d/{{ app_instance_id }}"
      mode: 0644

  - name: "enable site for {{ app_domain }}"
    file:
      state: link
      path: "/etc/{{ rev_proxy }}/sites-enabled/{{ app_instance_id }}.conf"
      src: "/etc/{{ rev_proxy }}/sites-available/{{ app_instance_id }}.conf"
    notify: reload {{ rev_proxy }}

  - name: "template for monitoring {{ app_domain }}"
    template:
      src: "app_monit.j2"
      dest: "/etc/monit/conf.d/{{ app_instance_id }}.conf"
    notify: reload monit
