---

  - name: "template for backup"
    template:
      src: app_backup_mysql.j2
      dest: "{{ backup_item_dir }}/20-{{ app_instance_id }}.sh"
      mode: 0640
    when: database_type == "mysql"

  - name: "template for backup"
    template:
      src: app_backup_postgres.j2
      dest: "{{ backup_item_dir }}/20-{{ app_instance_id }}.sh"
      mode: 0640
    when: database_type == "postgres"
