---

#  - name: "apt list --installed"
#    shell: "apt list --installed"
#    register: out

  - name: ""
    shell: "cat {{base_prod_ansible_log}}/inventory"
    register: out
    changed_when: False

  - debug: var=out.stdout
