---

  app_program: "Collabora"

  app_domain: "{{ collabora_domain }}"

  loolwsd_log_dest: "{{ base_prod_path }}/log/loolwsd"
  # fatal, critical, error, warning, notice, information, debug, trace
  collabora_log_level: "warning"

  #collabora_admin_user: "admin"
  #collabora_admin_password: "admin_password"

  apache_module_list: [
    "proxy",
    "proxy_http",
    "proxy_connect",
    "proxy_wstunnel",
    ]

  hunspell_module_list: [
    "hunspell-fr",
    "hunspell-en-us",
    "hunspell-en-gb",
    ]