---

  - include_role:
      name: dolibarr_instance
    vars:
      app_domain: "{{ item.dolibarr_domain}}"
      app_instance_id: "{{ item.dolibarr_instance_id }}"
      app_version: "{{ item.dolibarr_version }}"
      database_type: "{{ item.dolibarr_database_type }}"
    when: item.dolibarr_oldversion == ""
    loop: "{{ dolibarr_instances }}"

  - include_role:
      name: dolibarr_instance_upg
    vars:
      app_domain: "{{ item.dolibarr_domain}}"
      app_instance_id: "{{ item.dolibarr_instance_id }}"
      app_version: "{{ item.dolibarr_version }}"
      app_oldversion: "{{ item.dolibarr_oldversion }}"
      database_type: "{{ item.dolibarr_database_type }}"
    when: item.dolibarr_oldversion != ""
    loop: "{{ dolibarr_instances }}"
