---
  paquerette_name: "my-server"

  rev_proxy: "apache2"
  php_server: "yes"
  mariadb_mysql_server: "yes"
  mariadb_mysql: "mysql"
  mysql_root_password: "Veryverysecret"
  postgres_server: "yes"

  # Nextcloud
  nextcloud_domain: "mynextcloud.mydomain.org"
  nextcloud_oldversion: 12.0.4
  nextcloud_version: 12.0.5
  nextcloud_instance_id: "nc_mydomain"
  nextcloud_database_name: "{{ nextcloud_instance_id }}_db"

  # Mattermost
  mattermost_domain: "team.mydomain.org"
  mattermost_oldversion: 4.1.0
  mattermost_version: 4.6.0
  mattermost_instance_id: "mat_mydomain"

  #Collabora
  collabora_version: "2.1"
  collabora_domain: "mycollabora.mydomain.org"
  collabora_client_domains: ["mynextcloud\\.mydomain\\.org",]
  #collabora_secret: "Veryverysecret"
  collabora_port: 9980
  collabora_admin_user: "MelindaGates"
  collabora_admin_password: "letyouguess"

  # Dolibarr
  dolibarr_instances: [
    {
      dolibarr_domain: "myfirstdolibarr.mydomain.com",
      dolibarr_oldversion: "",
      dolibarr_version: "7.0.1",
      dolibarr_instance_id: "dol_1",
      dolibarr_database_type: "mysql", },
    {
      dolibarr_domain: "dolibarr.anotherdomain.com",
      dolibarr_oldversion: "7.0.0",
      dolibarr_version: "7.0.1",
      dolibarr_instance_id: "dol_2",
      dolibarr_database_type: "postgres", },
    ]