---

  # for mysql < 5.6
  mariadb_base_packages: ["mariadb-server", "python-mysqldb"]

  # for mysql >= 5.6
  #mariadb_base_packages: ["mysql-server", "python-mysqldb"]

  #### in group var
  #mysql_root_password: "moved"

#  - name: "Create a new database with name 'bobdata' "
#    mysql_db:
#      name: bobdata
#      state: present
#
#  - name: "Create a new user with all priviliges on database name 'bobdata' "
#    mysql_user:
#      name: bob
#      password: 12345
#      priv: 'bobdata.*:ALL,GRANT'
#      state: present
