---

  - name: "template log inventory - install"
    template:
      src: app_log.j2
      dest: "{{ base_prod_ansible_log }}/{{ app_instance_id }}.log"
      mode: 0600
    when: log_type == "install"

#  - name: "fetch check log"
#    fetch:
#      src: "{{ base_prod_ansible_log }}/{{ app_instance_id }}.log"
#      dest: "{{ app_instance_id }}.log"
#      flat: yes
#    when: log_type == "install"

  - name: "template log inventory - upgrade"
    template:
      src: app_log_upg.j2
      dest: "{{ base_prod_ansible_log }}/{{ app_instance_id }}.{{ app_version }}.log"
      mode: 0600
    when: log_type == "upgrade"

#  - name: "fetch check log"
#    fetch:
#      src: "{{ base_prod_ansible_log }}/{{ app_instance_id }}.{{ app_version }}.log"
#      dest: "{{ app_instance_id }}.log"
#      flat: yes
#    when: log_type == "upgrade"

  - name: "inventory"
    lineinfile:
      path: "{{ base_prod_ansible_log }}/inventory"
      regexp: '^"{{ app_instance_id }}"'
      line: '"{{ app_instance_id }}","{{ app_domain }}","{{ app_program }}","{{ app_version }}"'
      state: present
      create: yes
      mode: 0600
